const FILE_META = {
  README:{title:'Памятка оператора',kind:'SYSTEM NOTE',summary:'Короткое введение в терминал и намёк на скрытые файлы.',why:'Объясняет базовую механику: обычный ls показывает меньше, чем ls -la.',suggest:['cat /README','ls -la /']},
  LM005_CAM_025951:{title:'Кадр 02:59:51',kind:'CASE EVIDENCE',summary:'Запись камеры спальни из LM-005 с неучтённой аудиометкой.',why:'Даёт первый настоящий credential и запускает ветку повышения допуска.',suggest:['cat /cases/lm-005/cam_025951.log','auth коричневый вомбат'],important:true},
  LM005_POST:{title:'Постоперационный монитор LM-005',kind:'CASE EVIDENCE',summary:'Сигнал продолжался после официальной нейтрализации.',why:'Связывает LM-005 с NORM-0 и оставляет арифметический residue 1000-7.',suggest:['cat /cases/lm-005/post_operation.log','calc 1000-7'],important:true},
  Z006:{title:'Профиль Z-006',kind:'ENTITY TRACE',summary:'След арифметического паттерна и голосовых маркеров Зумерского демона.',why:'Подтверждает, что 1000-7 рассматривается системой как аномальный паттерн.',suggest:['cat /cases/lm-006/z006.log','calc 1000-7']},
  RESTRICTED_INDEX:{title:'Индекс сектора 17-B',kind:'INDEX',summary:'Оглавление закрытого сектора.',why:'Показывает, что часть кадровых записей исключена из обычной навигации.',suggest:['cat /restricted/index','ls -la /restricted']},
  AG02_FRAGMENT:{title:'Фрагмент AG-02',kind:'PERSONNEL ANOMALY',summary:'Карточка сотрудника, которого нет в кадровом реестре.',why:'Первый прямой кадровый след NORM-0.',suggest:['cat /restricted/ag-02.log','search NORM-0'],important:true},
  RESTRICTED_AUDIT:{title:'Скрытый аудит 17-B',kind:'HIDDEN AUDIT',summary:'Служебная запись об удалении трёх кадровых индексов.',why:'Рано сообщает, что AG-04, AG-09 и AG-13 не исчезли из данных полностью.',suggest:['cat /restricted/.audit','find / AG-0'],important:true},
  NORM0_ORIGIN:{title:'Первый вход NORM-0',kind:'BLACK RECORD',summary:'Невозможная сессия неизвестного оператора с датой до текущей NORM-OS.',why:'Главный переход от обычного архива к системному слою.',suggest:['cat /black/norm0_origin.log','decode 4e4f524d2d30','who are you'],important:true},
  PACKET17:{title:'Пакет 17',kind:'ENCODED PACKET',summary:'Небольшой Base64 payload без нормального маршрута.',why:'Позволяет самостоятельно проверить, что NORM-0 повторяется в разных каналах.',suggest:['cat /black/packet17.dat','decode Tk9STS0w']},
  BLACK_DELETED_INDEX:{title:'Кэш удалённого индекса',kind:'HIDDEN INDEX',summary:'Сохранившиеся inode-указатели на AG-04, AG-09 и AG-13.',why:'Показывает: удалены маршруты, а не сами блоки данных; указывает на /dev/n0.',suggest:['cat /black/.deleted-index','file /dev/n0'],important:true},
  BLACK_FINAL:{title:'Неавторизованный final.txt',kind:'ANOMALOUS NOTE',summary:'Файл, который N.O.R.M. не считает созданным собственной системой.',why:'Прямо подталкивает исследовать операционную систему, а не архив.',suggest:['cat /black/final.txt','ls -la /'],important:true},
  SYS_NORMCONF:{title:'Таблица монтирования NORM-OS',kind:'CONFIG',summary:'Конфигурация внутренних разделов и legacy-устройства.',why:'Содержит точный device и mountpoint для GHOSTFS.',suggest:['cat /etc/norm.conf','mount /dev/n0 /mnt/ghost'],important:true},
  SYS_RELEASE:{title:'Версия NORM-OS',kind:'SYSTEM INFO',summary:'Цепочка миграций базы и число неразрешённых старых томов.',why:'Даёт временную шкалу 1987→2004→2009→2013→2026.',suggest:['cat /etc/norm-release','stat /etc/norm-release']},
  SYS_HOSTS:{title:'Внутренние узлы',kind:'NETWORK CONFIG',summary:'Локальная карта node04, node17 и отключённого cold-archive.',why:'Показывает, что архив раньше был распределён по нескольким узлам.',suggest:['cat /etc/hosts','netstat']},
  SYS_PASSWD:{title:'Локальные учётные записи',kind:'SYSTEM ACCOUNT DB',summary:'Список системных пользователей и legacy UID агентов.',why:'Подтверждает существование домашних каталогов пропавших агентов и странную запись norm0.',suggest:['cat /etc/passwd','ls -la /home'],important:true},
  SYS_SSHCONF:{title:'Конфигурация старого cold-archive',kind:'NETWORK CONFIG',summary:'Отключённый SSH-маршрут к архивному узлу.',why:'Намекает, что observer.key в MIRROR — не просто декоративный трофей мира.',suggest:['cat /etc/ssh_config','ls -la /mirror']},
  SYS_AUTHLOG:{title:'Журнал авторизаций',kind:'FORENSIC LOG',summary:'Хронология исчезновения и посмертных событий AG-04/09/13.',why:'Связывает три пропавших записи ещё до монтирования GHOSTFS.',suggest:['cat /var/log/auth.log','grep AG-09 /var/log/auth.log'],important:true},
  SYS_BOOTLOG:{title:'Журнал загрузки',kind:'SYSTEM LOG',summary:'Показывает, что /dev/n0 обнаруживается при старте, но не монтируется политикой.',why:'Подтверждает, что GHOSTFS физически существует в NORM-OS.',suggest:['cat /var/log/boot.log','dmesg']},
  SYS_CORRELATION:{title:'Корреляционный журнал',kind:'ANALYSIS LOG',summary:'Автоматически связывает текущие LM-дела и три исторических инцидента.',why:'Первый файл, где старые и современные события оказываются в одном аналитическом контексте.',suggest:['cat /var/log/correlation.log','grep -R NORM-0 /var/log'],important:true},
  SYS_PURGE:{title:'История purge-задач',kind:'FORENSIC LOG',summary:'Журнал сокрытия кадровых маршрутов и самовосстановления указателя ghost volume.',why:'Показывает намеренное удаление навигации без уничтожения блоков.',suggest:['cat /var/log/purge.log','ls -la /black']},
  AG04_FIELDNOTE:{title:'Личная записка AG-04',kind:'HIDDEN PERSONAL FILE',summary:'Последняя техническая заметка Воронова о старом персональном томе.',why:'Прямо объясняет, что устройство нужно смонтировать, а не искать пароль.',suggest:['cat /home/ag-04/.fieldnote','mount /dev/n0 /mnt/ghost'],important:true},
  AG04_RADIO:{title:'Радиолаборатория AG-04',kind:'PERSONAL WORK FILE',summary:'31 Гц, правило не отвечать своему позывному и смещение 00:11:00.',why:'Первый персональный документ с общей 11-минутной аномалией.',suggest:['cat /home/ag-04/radio.txt','grep -R OFFSET /mnt/ghost/cases']},
  AG09_HISTORY:{title:'.bash_history AG-09',kind:'HIDDEN SHELL HISTORY',summary:'Реальная последовательность команд, которую Ланская использовала раньше игрока.',why:'Это практически найденный walkthrough внутри мира: strings → mount → grep.',suggest:['cat /home/ag-09/.bash_history','strings /dev/n0'],important:true},
  AG09_SESSION_CACHE:{title:'Кэш невозможной сессии',kind:'HIDDEN SESSION CACHE',summary:'Посмертный вход AG-09 и команда чтения транскрипта NO-17.',why:'Связывает смерть Ланской с делом Воронова и NORM-0.',suggest:['cat /home/ag-09/.cache/session','cat /var/log/auth.log'],important:true},
  AG13_LASTFRAME:{title:'Метаданные четвёртого кадра',kind:'HIDDEN CAMERA META',summary:'Камера ожидает 4 файла, хотя в каталоге осталось только 3.',why:'Предваряет дело IMG-13 и повторяет смещение 00:11:00.',suggest:['cat /home/ag-13/.camera/last_frame.meta','find /mnt/ghost/cases img-13'],important:true},
  NORM0_PROC:{title:'Процесс norm0',kind:'PROCFS RECORD',summary:'PID 0, владелец отсутствует, открыт дескриптор /dev/n0.',why:'Переводит NORM-0 из архивного идентификатора в нечто, похожее на системный процесс.',suggest:['cat /proc/norm0/status','ps'],important:true},
  NORM0_CMDLINE:{title:'cmdline norm0',kind:'PROCFS RECORD',summary:'Исполняемый файл отсутствует, но audit сообщает флаг сохранения удалённых маршрутов.',why:'Объясняет, почему некоторые удалённые записи продолжают существовать.',suggest:['cat /proc/norm0/cmdline','ls -la /mirror']},
  DEV_N0:{title:'Legacy block device n0',kind:'BLOCK DEVICE',summary:'Немонтированный бинарный том со строками GHOSTFS, агентами и историческими делами.',why:'Главная системная находка A-3: его нужно исследовать strings/xxd и смонтировать.',suggest:['file /dev/n0','strings /dev/n0','xxd /dev/n0','mount /dev/n0 /mnt/ghost'],important:true,binary:true},
  OPT_README:{title:'Служебные утилиты NORM',kind:'ADMIN README',summary:'Описание archive-index, correlation-daemon и reindex.',why:'Объясняет механику восстановления orphaned маршрутов.',suggest:['cat /opt/norm/README','cat /opt/norm/reindex.conf']},
  REINDEX_CONF:{title:'Конфигурация reindex',kind:'ADMIN CONFIG',summary:'Правила восстановления потерянных маршрутов из сохранившихся блоков.',why:'Содержит прямое имя будущего визуального маршрута /legacy-cases.',suggest:['cat /opt/norm/reindex.conf','reindex --orphaned'],important:true},
  TMP_N0:{title:'Временная метка NORM-0',kind:'HIDDEN TEMP FILE',summary:'Сессионная метка неизвестного процесса в /tmp.',why:'Не обязательна для прохождения; награда за привычку проверять скрытые временные файлы.',suggest:['cat /tmp/.n0-session','stat /tmp/.n0-session']},
  GHOST_INDEX:{title:'Индекс восстановленного тома',kind:'GHOSTFS INDEX',summary:'Перечень трёх личных дел и трёх исторических расследований.',why:'Оглавление большого A-4 слоя.',suggest:['cat /mnt/ghost/index','tree /mnt/ghost'],important:true},
  GHOST_AG04:{title:'Личное дело AG-04',kind:'RECOVERED DOSSIER',summary:'Илья Воронов: исчезновение в NO-17, тело не найдено.',why:'Даёт фрагмент OR и разблокирует часть восстановленного кадрового слоя.',suggest:['cat /mnt/ghost/personnel/ag-04.dos','download /mnt/ghost/personnel/ag-04.dos'],important:true},
  GHOST_AG09:{title:'Личное дело AG-09',kind:'RECOVERED DOSSIER',summary:'Вера Ланская: официальная смерть и посмертная авторизация.',why:'Даёт фрагмент PHE и связывает AR-31 с NO-17.',suggest:['cat /mnt/ghost/personnel/ag-09.dos','download /mnt/ghost/personnel/ag-09.dos'],important:true},
  GHOST_AG13:{title:'Личное дело AG-13',kind:'RECOVERED DOSSIER',summary:'Антон Руднев: ДТП и посмертные face-match события.',why:'Даёт фрагмент US и завершает тройку для токена ORPHEUS.',suggest:['cat /mnt/ghost/personnel/ag-13.dos','download /mnt/ghost/personnel/ag-13.dos'],important:true},
  AG04_MED:{title:'Медицинский допуск AG-04',kind:'PERSONNEL EVIDENCE',summary:'Последний осмотр до исчезновения; post-incident exam отсутствует.',why:'Подчёркивает, что официальная версия смерти не опиралась на найденное тело.',suggest:['cat /mnt/ghost/personnel/ag-04.med','download /mnt/ghost/personnel/ag-04.med']},
  AG09_DEATH:{title:'Кэш свидетельства о смерти AG-09',kind:'PERSONNEL EVIDENCE',summary:'Смерть закрыта без биологического подтверждения.',why:'Создаёт конкретное противоречие с последующей успешной авторизацией.',suggest:['cat /mnt/ghost/personnel/ag-09.death','download /mnt/ghost/personnel/ag-09.death'],important:true},
  AG13_CRASH:{title:'Сводка ДТП AG-13',kind:'PERSONNEL EVIDENCE',summary:'Карта камеры восстановлена, но система ожидает четвёртый кадр.',why:'Связывает физические вещи после ДТП с цифровой аномалией IMG-13.',suggest:['cat /mnt/ghost/personnel/ag-13.crash','download /mnt/ghost/personnel/ag-13.crash']},
  NO17_BRIEF:{title:'NO-17 / Пустая частота',kind:'CASE ROOT',summary:'Корневой файл дела об исчезновении AG-04 во время 11-минутного blackout.',why:'Один из трёх корней, обязательных для восстановления /legacy-cases.',suggest:['cat /mnt/ghost/cases/no-17/brief.log','evidence /mnt/ghost/cases/no-17'],important:true},
  NO17_SPECTRUM:{title:'Спектр NO-17',kind:'CASE EVIDENCE',summary:'CSV с несущей 31 Гц и повторяющимся offset 00:11:00.',why:'Формализует аномалию как измеряемые данные, а не только рассказ.',suggest:['cat /mnt/ghost/cases/no-17/spectrum.csv','download /mnt/ghost/cases/no-17/spectrum.csv']},
  NO17_TRANSCRIPT:{title:'Радиотранскрипт NO-17',kind:'CASE EVIDENCE',summary:'Через 11 минут после исчезновения звучит голос, похожий на AG-04.',why:'Один из самых содержательных файлов ветки Воронова.',suggest:['cat /mnt/ghost/cases/no-17/transcript.txt','download /mnt/ghost/cases/no-17/transcript.txt'],important:true},
  AR31_BRIEF:{title:'AR-31 / Пепельный индекс',kind:'CASE ROOT',summary:'Корневой файл архивного пожара и официальной смерти AG-09.',why:'Второй обязательный корень для восстановления /legacy-cases.',suggest:['cat /mnt/ghost/cases/ar-31/brief.log','evidence /mnt/ghost/cases/ar-31'],important:true},
  AR31_FIRE:{title:'Пожарный отчёт AR-31',kind:'CASE EVIDENCE',summary:'Повреждения архива, жетон AG-09 и часы терминала +11 минут.',why:'Показывает, что временной сдвиг повторяется уже в другом типе события.',suggest:['cat /mnt/ghost/cases/ar-31/fire_report.txt','download /mnt/ghost/cases/ar-31/fire_report.txt']},
  AR31_AUTH:{title:'Посмертный auth trace AG-09',kind:'CASE EVIDENCE',summary:'Успешная авторизация спустя 19 месяцев после официальной смерти.',why:'Внутри сессии AG-09 открывает транскрипт NO-17 и оставляет фразу-предупреждение.',suggest:['cat /mnt/ghost/cases/ar-31/auth_trace.log','download /mnt/ghost/cases/ar-31/auth_trace.log'],important:true},
  IMG13_BRIEF:{title:'IMG-13 / Четвёртый кадр',kind:'CASE ROOT',summary:'Корневой файл дела AG-13: 3 видимых файла при 4 ожидаемых.',why:'Третий обязательный корень для восстановления /legacy-cases.',suggest:['cat /mnt/ghost/cases/img-13/brief.log','evidence /mnt/ghost/cases/img-13'],important:true},
  IMG13_FRAME_META:{title:'Метаданные отсутствующего кадра',kind:'CASE EVIDENCE',summary:'Самого файла нет, но его capture/index timestamps и face-match сохранились.',why:'Доказывает цифровое существование удалённого кадра и опять показывает +00:11:00.',suggest:['cat /mnt/ghost/cases/img-13/frame_04.meta','download /mnt/ghost/cases/img-13/frame_04.meta'],important:true},
  IMG13_FACEMATCH:{title:'Face-match журнал IMG-13',kind:'CASE EVIDENCE',summary:'Три посмертных совпадения лица AG-13 на кэше отсутствующего кадра.',why:'После третьего совпадения неизвестный процесс удаляет кадровую карточку AG-13.',suggest:['cat /mnt/ghost/cases/img-13/facematch.log','download /mnt/ghost/cases/img-13/facematch.log'],important:true},
  GHOST_FRAGMENTS:{title:'Фрагменты привилегированного токена',kind:'HIDDEN KEY FILE',summary:'OR + PHE + US в порядке кадрового индекса.',why:'Собирается в ORPHEUS и открывает A-5 через sudo.',suggest:['cat /mnt/ghost/.fragments','sudo unlock ORPHEUS'],important:true},
  GHOST_ROUTE_MAP:{title:'Скрытая карта legacy-маршрутов',kind:'HIDDEN ROUTE MAP',summary:'Связывает три дела, трёх агентов и удалённый маршрут /legacy-cases.',why:'Показывает, что данные живы, но визуальный маршрут был удалён.',suggest:['cat /mnt/ghost/.route-map','ls -la /mirror'],important:true},
  MIRROR_INDEX:{title:'Индекс MIRROR',kind:'MIRROR INDEX',summary:'Слой записей, удалённых из обычной навигации.',why:'Подтверждает принцип мира: удаление маршрута не равно уничтожению записи.',suggest:['cat /mirror/index','ls -la /mirror']},
  MIRROR_CONTINUITY:{title:'Отчёт о непрерывности',kind:'LORE RECORD',summary:'Разделяет исторические подразделения и современную группу LM.',why:'Фиксирует канон: старые дела расширяют историю Н.О.Р.М., не заменяя события выпусков.',suggest:['cat /mirror/personnel.continuity','download /mirror/personnel.continuity']},
  MIRROR_NORM0:{title:'Снимок NORM-0',kind:'MIRROR SNAPSHOT',summary:'Две конкурирующие гипотезы о природе NORM-0.',why:'Главная лорная награда A-5 без окончательного ответа.',suggest:['cat /mirror/norm0.snapshot','download /mirror/norm0.snapshot'],important:true},
  OBSERVER_KEY:{title:'Observer Key',kind:'TROPHY',summary:'Коллекционный файл, подтверждающий достижение A-5 текущей сессией.',why:'Это именно награда: его можно вынести из NORM-OS как локальный трофей.',suggest:['cat /mirror/observer.key','download /mirror/observer.key'],important:true,trophy:true},
  MIRROR_DELETED_ROUTES:{title:'Таблица удалённых маршрутов',kind:'MIRROR ROUTING',summary:'Маршруты, которые удалены из UI, но чьи блоки сохранились.',why:'Прямо сообщает про orphaned /legacy-cases и утилиту reindex.',suggest:['cat /mirror/deleted.routes','cat /opt/norm/reindex.conf'],important:true},
  MIRROR_ORPHANED:{title:'Скрытая orphan table',kind:'HIDDEN ROUTING',summary:'Условия восстановления /legacy-cases.',why:'Последнее доказательство перед командой reindex --orphaned.',suggest:['cat /mirror/.orphaned','reindex --orphaned'],important:true},
  NO17_SHADOW:{title:'Shadow NO-17',kind:'MIRROR SHADOW',summary:'Закрытие дела NORM-0 и поздний сигнал позывного AG-04.',why:'Показывает, что исчезновение Воронова никогда не было реально разрешено.',suggest:['cat /mirror/cases/no-17.shadow','download /mirror/cases/no-17.shadow']},
  AR31_SHADOW:{title:'Shadow AR-31',kind:'MIRROR SHADOW',summary:'NORM-0 закрыл смерть без биологического подтверждения.',why:'Поднимает вопрос, кто и зачем оформил смерть AG-09.',suggest:['cat /mirror/cases/ar-31.shadow','download /mirror/cases/ar-31.shadow']},
  IMG13_SHADOW:{title:'Shadow IMG-13',kind:'MIRROR SHADOW',summary:'Удаление AG-13 после третьего face-match; inode кадра всё ещё существует.',why:'Сохраняет надежду, что отсутствующий кадр физически не уничтожен.',suggest:['cat /mirror/cases/img-13.shadow','download /mirror/cases/img-13.shadow']},
}

const DIR_META = {
  '/': ['ROOT','Корень NORM-OS. После A-3 именно здесь начинается системное исследование.'],
  '/cases':['CURRENT CASES','Текущие публичные дела современной группы LM.'],
  '/cases/lm-005':['LM-005','Материалы Ночного Душнилы: камера и постоперационный след.'],
  '/cases/lm-006':['LM-006','Материалы Зумерского демона и паттерна 1000-7.'],
  '/restricted':['RESTRICTED 17-B','Закрытые кадровые и постоперационные фрагменты. Используйте ls -la.'],
  '/black':['BLACK ARCHIVE','Записи NORM-0 и удалённые индексы. Используйте ls -la.'],
  '/etc':['SYSTEM CONFIG','Конфигурация NORM-OS: монтирование, аккаунты, узлы и recovery-настройки.'],
  '/var/log':['FORENSIC LOGS','Системные журналы. Здесь удобнее всего искать grep -R по агентам и NORM-0.'],
  '/home':['LEGACY HOMES','Домашние каталоги старых сотрудников. Скрытые файлы важнее обычных.'],
  '/home/ag-04':['AG-04 HOME','Личные технические заметки Ильи Воронова.'],
  '/home/ag-09':['AG-09 HOME','Shell-history и кэш невозможной сессии Веры Ланской.'],
  '/home/ag-13':['AG-13 HOME','Скрытые метаданные камеры Антона Руднева.'],
  '/proc/norm0':['NORM-0 PROCFS','Состояние неизвестного системного процесса/маркера.'],
  '/dev':['DEVICES','Системные устройства. /dev/n0 — legacy block device.'],
  '/opt/norm':['ADMIN TOOLS','Служебные утилиты NORM-OS, включая reindex.'],
  '/tmp':['TEMP','Временные данные текущей и неизвестной сессии. Используйте ls -la.'],
  '/mnt':['MOUNTS','Точки монтирования внешних/legacy томов.'],
  '/mnt/ghost':['GHOSTFS','Восстановленный персональный том: люди, дела, ключи и скрытые карты.'],
  '/mnt/ghost/personnel':['RECOVERED PERSONNEL','Шесть кадровых файлов: три досье и три подтверждающих документа.'],
  '/mnt/ghost/cases':['HISTORICAL CASES','Три старых внутренних дела, удалённых из обычного UI.'],
  '/mnt/ghost/cases/no-17':['NO-17','Пустая частота: brief + измерения + радиотранскрипт.'],
  '/mnt/ghost/cases/ar-31':['AR-31','Пепельный индекс: brief + пожарный отчёт + посмертный auth trace.'],
  '/mnt/ghost/cases/img-13':['IMG-13','Четвёртый кадр: brief + metadata + face-match журнал.'],
  '/mirror':['MIRROR','Удалённые маршруты, shadow-копии и награды A-5. Используйте ls -la.'],
  '/mirror/cases':['MIRROR SHADOW CASES','Скрытые post-closure копии трёх исторических дел.'],
}

export function getFileMeta(file){
  if(!file) return null
  const fallbackKind=file.binary?'BINARY OBJECT':file.system?'SYSTEM FILE':'ARCHIVE FILE'
  return FILE_META[file.id] || {
    title:file.id,
    kind:fallbackKind,
    summary:'Внутренний файл NORM-OS. Его можно прочитать, исследовать метаданные и экспортировать.',
    why:'Необязательный контекст или служебный след. Используйте INSPECT, CAT, STAT и DOWNLOAD.',
    suggest:[`cat ${file.path}`,`stat ${file.path}`,`download ${file.path}`],
  }
}

export function getDirectoryMeta(path){
  const item=DIR_META[path]
  return item?{title:item[0],summary:item[1]}:{title:'DIRECTORY',summary:'Каталог внутренней файловой системы NORM-OS.'}
}

export function isTrophyFile(file){return Boolean(getFileMeta(file)?.trophy)}
