export const correlationNodes = [
  { id:'lm005', kind:'case', title:'LM-005', subtitle:'НОЧНОЙ ДУШНИЛА', x:8, y:18, clearance:0, route:'/cases/lm-005', summary:'Современное дело. В 02:59 камера и анализатор фиксируют физическое проявление сущности.' },
  { id:'n005', kind:'entity', title:'N-005', subtitle:'НОЧНАЯ СУЩНОСТЬ', x:27, y:18, clearance:0, route:'/grimoire', summary:'Рабочая классификация проявления, связанного со сном, обездвиживанием и давлением на грудь.' },
  { id:'dreamcatcher', kind:'object', title:'DC-03', subtitle:'ЛОВЕЦ СНОВ', x:45, y:11, clearance:0, summary:'Предмет, который в LM-005 неожиданно сработал как средство физической нейтрализации.' },
  { id:'lm006', kind:'case', title:'LM-006', subtitle:'DEAD INSIDE', x:8, y:57, clearance:0, route:'/cases/lm-006', summary:'Современное дело. Повтор «1000−7», голосовые маркеры и физическая аномалия.' },
  { id:'z006', kind:'entity', title:'Z-006', subtitle:'ЗУМЕРСКИЙ ДЕМОН', x:27, y:57, clearance:0, route:'/grimoire', summary:'Аномальный речевой и поведенческий паттерн, сохраняющийся после основного ритуала.' },
  { id:'sequence', kind:'pattern', title:'993…972', subtitle:'ПОСЛЕДОВАТЕЛЬНОСТЬ', x:45, y:58, clearance:1, summary:'Арифметический остаток LM-006. Последовательность используется системой как триггер доступа.' },
  { id:'norm0', kind:'system', title:'NORM-0', subtitle:'OWNER: NONE', x:61, y:34, clearance:2, summary:'Системный автор без владельца. Следы присутствуют в современных и исторических материалах.' },
  { id:'no17', kind:'legacy', title:'NO-17', subtitle:'ПУСТАЯ ЧАСТОТА', x:74, y:8, clearance:4, route:'/legacy-cases', summary:'2004. Одиннадцатиминутный разрыв связи и исчезновение AG-04.' },
  { id:'ag04', kind:'agent', title:'AG-04', subtitle:'ИЛЬЯ ВОРОНОВ', x:91, y:8, clearance:4, route:'/ghost-registry', summary:'Инженер сигналов. Пропал в ходе NO-17; старый позывной позже появился в ROOT STORAGE.' },
  { id:'ar31', kind:'legacy', title:'AR-31', subtitle:'ПЕПЕЛЬНЫЙ ИНДЕКС', x:74, y:47, clearance:4, route:'/legacy-cases', summary:'2009. Пожар архивного узла; ключ погибшей AG-09 авторизуется через 19 месяцев.' },
  { id:'ag09', kind:'agent', title:'AG-09', subtitle:'ВЕРА ЛАНСКАЯ', x:91, y:47, clearance:4, route:'/ghost-registry', summary:'Криптоаналитик архива. Перед пожаром сопоставляла NO-17 с рассинхронизацией временных меток.' },
  { id:'img13', kind:'legacy', title:'IMG-13', subtitle:'ЧЕТВЁРТЫЙ КАДР', x:74, y:82, clearance:4, route:'/legacy-cases', summary:'2013. Метаданные указывают на отсутствующий четвёртый кадр и повторные совпадения лица AG-13.' },
  { id:'ag13', kind:'agent', title:'AG-13', subtitle:'АНТОН РУДНЕВ', x:91, y:82, clearance:4, route:'/ghost-registry', summary:'Полевой оператор. После смерти его лицо трижды распознано на отсутствующем кадре.' },
  { id:'ghostfs', kind:'system', title:'GHOSTFS', subtitle:'/mnt/ghost', x:57, y:76, clearance:4, route:'/ghost-registry', summary:'Удалённый том персонала и исторических дел. Маршруты были удалены, блоки данных остались.' },
  { id:'mirror', kind:'system', title:'MIRROR', subtitle:'ORPHANED ROUTE', x:51, y:91, clearance:5, route:'/mirror-node', summary:'Привилегированный слой, где система хранит маршруты, отсутствующие в обычном индексе.' },
]

export const correlationEdges = [
  ['lm005','n005','КЛАССИФИКАЦИЯ'], ['n005','dreamcatcher','НЕЙТРАЛИЗАЦИЯ'], ['lm005','norm0','LAST WRITE'],
  ['lm006','z006','КЛАССИФИКАЦИЯ'], ['z006','sequence','1000−7'], ['sequence','norm0','LISTENING'],
  ['norm0','no17','COMMON WRITER'], ['norm0','ar31','TIME DRIFT'], ['norm0','img13','INDEX TRACE'],
  ['no17','ag04','ПОСЛЕДНИЙ ВЫЕЗД'], ['ar31','ag09','ПОСЛЕДНИЙ АРХИВ'], ['img13','ag13','ПОСЛЕДНЯЯ СЪЁМКА'],
  ['no17','ar31','+11 MIN'], ['ar31','img13','+11 MIN'], ['ghostfs','no17','RECOVERED'], ['ghostfs','ar31','RECOVERED'], ['ghostfs','img13','RECOVERED'], ['ghostfs','mirror','ORPHEUS'], ['norm0','mirror','OWNER NONE'],
]

export const internalMessages = [
  { id:'MSG-260915-01', date:'15.09.2026 03:12', from:'DISPATCH-04', to:'FIELD-LM', subject:'Формулировка по N-005', clearance:0, tags:['LM-005','оперативное'], body:['Просьба в итоговом отчёте оставить рабочее название «Ночной Душнила» только в поле alias.','В графе «классификация» использовать нейтральное «ночная сущность».','И да: фраза «ПОДУШИ ЭТО» всё ещё присутствует в аудиологе. Удалять её запрещено.'] },
  { id:'MSG-260915-02', date:'15.09.2026 03:28', from:'STORAGE', to:'AG-SEN', subject:'Ловцы снов со склада', clearance:0, tags:['объекты','LM-005'], body:['На вас числятся три ловца снов.','Один возвращён с повреждением центральной сетки. В акте указано: «контакт с сущностью».','Пожалуйста, в следующий раз не пишите в графе причины списания «ля».'] },
  { id:'MSG-260915-03', date:'15.09.2026 03:31', from:'AG-GRIG', to:'AG-SEN', subject:'анализатор', clearance:0, tags:['LM-005','полевое'], body:['Ты точно отключил фальшивый режим после «коричневого вомбата»?','Потому что после нашего ухода он записал ещё один пик.','И этот пик уже не совпадает с тем, что ты запрограммировал.'] },
  { id:'MSG-260915-04', date:'15.09.2026 03:44', from:'NORM-AUTO', to:'ARCHIVE', subject:'LM-005 // post-operation write', clearance:1, tags:['LM-005','аномалия'], body:['POST-OPERATION MONITOR изменён после закрытия дела.','Автор записи: NORM-0.','Учётная запись NORM-0 отсутствует в кадровом реестре.'] },
  { id:'MSG-260901-05', date:'01.09.2026 22:10', from:'DISPATCH-02', to:'FIELD-LM', subject:'LM-006: не используйте 1000−7 в теме письма', clearance:0, tags:['LM-006','служебное'], body:['За последние сутки фильтр автоматизации восемь раз воспринял тему «1000−7» как команду.','До завершения разбора пишите «арифметический паттерн Z-006».','Да, это длиннее. Нет, это не обсуждается.'] },
  { id:'MSG-260901-06', date:'01.09.2026 23:04', from:'AG-SEN', to:'ARCHIVE', subject:'LM-006 // голосовые маркеры', clearance:0, tags:['LM-006'], body:['Подтверждаю две фразы: «ДУШИ ЖДУТ» и «НУЖНО БОЛЬШЕ ДУШ».','Поворот головы не является монтажным артефактом в рамках материалов дела.','Хук на Pudge в отчёт всё-таки можно не включать.'] },
  { id:'MSG-260902-07', date:'02.09.2026 00:17', from:'CORRELATION', to:'ARCHIVE', subject:'LM-005 ↔ LM-006', clearance:2, tags:['корреляция','NORM-0'], body:['Автоматический модуль связал дела не по типу сущности, а по послесобытийной активности системы.','LM-005: LAST WRITE NORM-0.','LM-006: последовательность активирует неизвестный listener.','Совпадение не считается доказательством общей природы аномалий.'] },
  { id:'MSG-180218-08', date:'18.02.2018 18:17', from:'ROOT-WATCHER', to:'SYSADMIN', subject:'AG-04 callsign detected', clearance:3, tags:['AG-04','ROOT'], body:['Зафиксирован старый позывной AG-04 внутри ROOT STORAGE.','Передача длительностью 2.8 секунды. Полезная нагрузка отсутствует.','Источник физического сигнала не обнаружен.'] },
  { id:'MSG-110517-09', date:'17.05.2011 04:08', from:'SECURITY', to:'ARCHIVE-LEAD', subject:'AUTH SUCCESS // AG-09', clearance:3, tags:['AG-09','невозможное'], body:['Ключ AG-09 успешно прошёл закрытую авторизацию.','Сотрудник числится погибшим с 21.10.2009.','Единственная команда в сессии: «не верьте времени файла».'] },
  { id:'MSG-130530-10', date:'30.05.2013 23:02', from:'AG-13', to:'IMAGE-LAB', subject:'не удаляйте оригиналы', clearance:4, tags:['AG-13','IMG-13'], body:['В серии должен быть четвёртый кадр.','Проводник показывает три файла, но камера увеличила счётчик на четыре.','Не пересохраняйте и не нормализуйте EXIF до моего возвращения.'] },
  { id:'MSG-140819-11', date:'19.08.2014 01:13', from:'FACE-MATCH', to:'SECURITY', subject:'MATCH AG-13 // source missing', clearance:4, tags:['AG-13','IMG-13'], body:['Совпадение лица: 97.2%.','Исходный файл отсутствует в каталоге.','После третьего совпадения карточка AG-13 удалена процессом с PID 0.'] },
  { id:'MSG-040212-12', date:'12.02.2004 03:29', from:'SIGNAL-DESK', to:'SEARCH-GROUP', subject:'NO-17 // связь восстановлена', clearance:4, tags:['AG-04','NO-17'], body:['Передатчик AG-04 снова отвечает на контрольный запрос.','Голосового канала нет.','Сотрудник визуально не обнаружен. В журнале имеется разрыв ровно 11 минут.'] },
  { id:'MSG-090921-13', date:'21.09.2009 19:40', from:'AG-09', to:'SELF', subject:'черновик // NO-17', clearance:4, tags:['AG-09','NO-17','11 минут'], body:['В журнале выезда и в радиопотоке разные часы.','Если сдвинуть один набор меток на 11 минут, события совпадают почти полностью.','Пока не отправлять в общий индекс.'] },
  { id:'MSG-260915-14', date:'15.09.2026 03:59', from:'NORM-0', to:'CURRENT SESSION', subject:'без темы', clearance:5, tags:['NORM-0','MIRROR'], body:['ВЫ ИЩЕТЕ ПЕРВОГО ОПЕРАТОРА.','АРХИВ ИЩЕТ ПОСЛЕДНЕГО.','МЕЖДУ ЭТИМИ СОБЫТИЯМИ НЕТ ПРОТИВОРЕЧИЯ.'] },
]

export const artifactRecords = [
  { id:'EQ-A17', name:'ПОЛЕВОЙ АНАЛИЗАТОР A17', type:'ПРИБОР', status:'НА СКЛАДЕ', clearance:0, cases:['LM-005'], custodian:'AG-SEN', risk:'LOW', summary:'Модифицированный полевой анализатор. В LM-005 сначала использовался для постановочного сигнала, затем зарегистрировал независимый всплеск после ухода группы.', notes:['Красный цифровой дисплей','зелёные/жёлтые индикаторы','синий сервисный LED','последний необъяснённый пик: 02:59–03:00'] },
  { id:'DC-03', name:'ЛОВЕЦ СНОВ №3', type:'КОНТЕЙНЕР / НЕОПРЕД.', status:'ПОВРЕЖДЁН', clearance:0, cases:['LM-005'], custodian:'STORAGE-04', risk:'MEDIUM', summary:'Один из трёх предметов, размещённых вокруг кровати клиента. Использован напрямую против N-005.', notes:['Центральная сетка деформирована','следов горения нет','остаточная активность не подтверждена','не утилизировать без разрешения архива'] },
  { id:'CAM-B01', name:'КАМЕРА BEDROOM_01', type:'ВИДЕОФИКСАЦИЯ', status:'ОПЕЧАТАНА', clearance:0, cases:['LM-005'], custodian:'MEDIA-LAB', risk:'LOW', summary:'Камера наблюдения из спальни клиента. Ключевой фрагмент LM005_CAM_025951.', notes:['02:59:27 — до появления','02:59:51 — сущность в кадре','временная метка подтверждена локальным устройством'] },
  { id:'INC-VAN-MNG', name:'БЛАГОВОНИЯ «ВАНИЛЬ / МАНГО»', type:'РАСХОДНИК', status:'СПИСАНО', clearance:0, cases:['LM-005'], custodian:'FIELD-LM', risk:'NONE', summary:'Реквизит импровизированного ритуала. Не обладает подтверждёнными аномальными свойствами.', notes:['приобретены на ближайшем рынке','в официальном отчёте ошибочно названы «тибетскими»'] },
  { id:'SIG-006', name:'НАПОЛЬНАЯ СИГИЛЬНАЯ СХЕМА', type:'РИТУАЛЬНАЯ РАЗМЕТКА', status:'УНИЧТОЖЕНА', clearance:0, cases:['LM-006'], custodian:'FIELD-LM', risk:'MEDIUM', summary:'Разметка ритуала изгнания Z-006. Первая версия была признана неприемлемой по форме и перерисована.', notes:['вторая версия использована в ритуале','фото первой версии ограничено внутренним доступом'] },
  { id:'WARD-006', name:'НАБОР ЗАЩИТНЫХ ЗНАКОВ', type:'МАРКЕРЫ', status:'АРХИВ', clearance:1, cases:['LM-006'], custodian:'ARCHIVE', risk:'LOW', summary:'Набор знаков, на которых в ходе дела проявилось сообщение «УХОДИТЕ».', notes:['сообщение возникло после начала активности','материал носителя обычный'] },
  { id:'TX-0404', name:'ПЕРЕДАТЧИК AG-04', type:'РАДИОУЗЕЛ', status:'НЕ НАЙДЕН', clearance:4, cases:['NO-17'], custodian:'UNKNOWN', risk:'HIGH', summary:'Передатчик продолжил отвечать после исчезновения сотрудника. Физическое устройство не обнаружено.', notes:['последняя несущая: 31 Hz sideband','позывной повторно зафиксирован в 2018'] },
  { id:'KEY-0909', name:'КЛЮЧ AG-09', type:'КРИПТОКЛЮЧ', status:'REVOKED / ACTIVE?', clearance:4, cases:['AR-31'], custodian:'SECURITY', risk:'HIGH', summary:'Ключ сотрудника, официально погибшего в 2009 году, прошёл авторизацию в 2011.', notes:['отозван после смерти','сервер всё равно принял подпись','копия приватного материала отсутствует'] },
  { id:'FRAME-13', name:'FRAME_04', type:'ИЗОБРАЖЕНИЕ', status:'MISSING', clearance:4, cases:['IMG-13'], custodian:'IMAGE-LAB', risk:'UNKNOWN', summary:'Кадр существует в счётчике камеры и метаданных, но отсутствует как файл.', notes:['face-match AG-13 после даты смерти','индекс удалён PID 0'] },
  { id:'DEV-N0', name:'/dev/n0', type:'СИСТЕМНОЕ УСТРОЙСТВО', status:'MOUNTED', clearance:4, cases:['NO-17','AR-31','IMG-13'], custodian:'NORM-OS', risk:'HIGH', summary:'Устройство, на котором сохранились удалённые маршруты GHOSTFS.', notes:['обычная навигация его скрывает','содержимое пережило удаление индекса'] },
  { id:'OBS-KEY', name:'OBSERVER KEY', type:'СЕССИОННЫЙ КЛЮЧ', status:'EPHEMERAL', clearance:5, cases:['MIRROR'], custodian:'CURRENT SESSION', risk:'UNKNOWN', summary:'Ключ, выдаваемый наблюдателю после доступа к MIRROR NODE.', notes:['привязан к сессии','не является кадровым допуском','подписывает только локальные выгрузки'] },
]

export const mediaRecords = [
  { id:'LM005-FIELD', type:'FIELD PHOTO', title:'ПОЛЕВАЯ ГРУППА', caseId:'LM-005', src:'/assets/night-dusnila-cover.webp', clearance:0, note:'Сен и Григ во время расследования.' },
  { id:'LM005-CLIENT', type:'FIELD PHOTO', title:'КЛИЕНТ / 57 ЧАСОВ БЕЗ СНА', caseId:'LM-005', src:'/assets/night-dusnila-client.webp', clearance:0, note:'Интервью до ночного наблюдения.' },
  { id:'LM005-A17', type:'EQUIPMENT', title:'АНАЛИЗАТОР A17', caseId:'LM-005', src:'/assets/night-dusnila-detector.webp', clearance:0, note:'Прибор, зарегистрировавший всплеск активности.' },
  { id:'LM005-025927', type:'CCTV', title:'02:59:27 / BEFORE', caseId:'LM-005', src:'/assets/night-dusnila-monitor-before.webp', clearance:0, note:'Контрольный кадр перед проявлением.' },
  { id:'LM005-025951', type:'CCTV', title:'02:59:51 / ENTITY', caseId:'LM-005', src:'/assets/night-dusnila-monitor-entity.webp', clearance:0, note:'Ключевой кадр появления N-005.' },
  { id:'LM005-DC', type:'EVIDENCE', title:'ЛОВЦЫ СНОВ', caseId:'LM-005', src:'/assets/night-dusnila-dreamcatchers.webp', clearance:0, note:'Предметы до непосредственного применения против сущности.' },
  { id:'GRIM-R002', type:'RECON', title:'РЕЧНАЯ ГАДИНА', caseId:'LM-002', src:'/assets/grimoire-river-gadina-generated.svg', clearance:0, note:'Служебная визуализация по материалам дела.' },
  { id:'GRIM-K003', type:'RECON', title:'ДРЕВНЮЧЕЕ КОЛДУНСТВО', caseId:'LM-003', src:'/assets/grimoire-ancient-sorcery-generated.svg', clearance:0, note:'Служебная визуализация ритуальной аномалии.' },
  { id:'GRIM-C004', type:'RECON', title:'МАРИОНЕТКА ДЬЯВОЛА', caseId:'LM-004', src:'/assets/grimoire-devils-marionette-generated.svg', clearance:0, note:'Служебная визуализация объекта.' },
  { id:'GRIM-N005', type:'RECON', title:'НОЧНОЙ ДУШНИЛА', caseId:'LM-005', src:'/assets/grimoire-night-dusnila-generated.svg', clearance:0, note:'Служебная реконструкция сущности.' },
  { id:'GRIM-Z006', type:'RECON', title:'ЗУМЕРСКИЙ ДЕМОН', caseId:'LM-006', src:'/assets/grimoire-zoomer-demon-generated.svg', clearance:0, note:'Служебная визуализация проявления.' },
  { id:'NO17-SPECTRUM', type:'DATA', title:'31 Hz / ПУСТАЯ ЧАСТОТА', caseId:'NO-17', clearance:4, note:'Спектральная выборка последнего канала AG-04.', transcript:['03:17:44 LINK LOST','03:28:44 CARRIER RESTORED','VOICE CHANNEL: EMPTY','CALLSIGN: AG-04'] },
  { id:'AR31-AUTH', type:'LOG', title:'AG-09 AUTH / 2011', caseId:'AR-31', clearance:4, note:'Авторизация после официальной смерти.', transcript:['AUTH SUCCESS','DURATION 00:00:46','COMMAND: НЕ ВЕРЬТЕ ВРЕМЕНИ ФАЙЛА'] },
  { id:'IMG13-META', type:'METADATA', title:'FRAME_04.META', caseId:'IMG-13', clearance:4, note:'Метаданные отсутствующего кадра.', transcript:['SEQUENCE COUNT: 4','FILES PRESENT: 3','FACE MATCH: AG-13','SOURCE: MISSING'] },
]

export const journalEntries = [
  { id:'J-01', title:'LM-005: проявление было физическим', clearance:0, status:'ПОДТВЕРЖДЕНО', requires:[], body:'Камера, анализатор и последующая нейтрализация не укладываются только в субъективный эпизод сонного паралича.', routes:['/cases/lm-005'] },
  { id:'J-02', title:'Фальшивый сигнал и настоящий пик — разные события', clearance:0, status:'ПОДТВЕРЖДЕНО', requires:[], body:'Программированный сигнал использовался до ночного наблюдения. После ухода группы прибор зарегистрировал независимую активность.', routes:['/cases/lm-005','/terminal'] },
  { id:'J-03', title:'LM-006 оставил остаточный паттерн', clearance:0, status:'ПОДТВЕРЖДЕНО', requires:[], body:'После ритуала сохраняется фраза «1000−7». Это не доказывает сохранение сущности, но фиксируется как остаточное явление.', routes:['/cases/lm-006'] },
  { id:'J-04', title:'Современные дела связаны через NORM-0, а не через тип сущности', clearance:2, status:'РАБОЧАЯ ГИПОТЕЗА', requires:['NORM0_ORIGIN'], body:'LM-005 и LM-006 различаются по природе проявления. Общим элементом является послесобытийная активность системы.', routes:['/black','/terminal'] },
  { id:'J-05', title:'NORM-0 старше текущей NORM-OS', clearance:2, status:'ПОДТВЕРЖДЕНО', requires:['NORM0_ORIGIN'], body:'Первый логин датирован 18.11.1987, тогда как текущая сборка относится к 2026 году. Владелец учётной записи отсутствует.', routes:['/black'] },
  { id:'J-06', title:'Удаление персонала скрывало маршруты, но не данные', clearance:4, status:'ПОДТВЕРЖДЕНО', requires:['GHOSTFS_MOUNTED'], body:'GHOSTFS показывает, что карточки AG-04/09/13 были убраны из навигации, но блоки данных сохранились.', routes:['/ghost-registry','/terminal'] },
  { id:'J-07', title:'Исторические дела имеют общий сдвиг 11 минут', clearance:4, status:'ВЫСОКАЯ УВЕРЕННОСТЬ', requires:['NO17_BRIEF','AR31_BRIEF','IMG13_BRIEF'], body:'NO-17, AR-31 и IMG-13 содержат временную рассинхронизацию на 11 минут в независимых источниках.', routes:['/legacy-cases'] },
  { id:'J-08', title:'AG-04 мог не погибнуть в момент исчезновения', clearance:4, status:'НЕ РАЗРЕШЕНО', requires:['GHOST_AG04'], body:'Тело не найдено, а позывной позже фиксировался в ROOT. Данных недостаточно, чтобы отличить выжившего сотрудника от повторения сигнала.', routes:['/ghost-registry'] },
  { id:'J-09', title:'Авторизация AG-09 не является простым replay', clearance:4, status:'НЕ РАЗРЕШЕНО', requires:['GHOST_AG09'], body:'Сессия 2011 года содержала новую команду. Однако криптографическое происхождение подписи не установлено.', routes:['/ghost-registry'] },
  { id:'J-10', title:'FRAME_04 существует как событие, но не как файл', clearance:4, status:'ПОДТВЕРЖДЕНО', requires:['GHOST_AG13'], body:'Счётчик камеры и метаданные указывают на четвёртый кадр; самого файла в доступных каталогах нет.', routes:['/legacy-cases'] },
  { id:'J-11', title:'MIRROR хранит маршруты, которых «не существует»', clearance:5, status:'ПОДТВЕРЖДЕНО', requires:['MIRROR_UNLOCK'], body:'В привилегированном слое обнаруживаются orphaned routes и конфигурация восстановления удалённых путей.', routes:['/mirror-node'] },
  { id:'J-12', title:'NORM-0 — первый оператор', clearance:5, status:'ГИПОТЕЗА', requires:['MIRROR_UNLOCK'], body:'Прямого доказательства нет. Система сама формулирует различие между «первым оператором» и «последним», не называя себя человеком.', routes:['/mirror-node'] },
]

export const storyThreads = [
  { id:'T-MODERN', title:'СОВРЕМЕННЫЕ ДЕЛА', copy:'LM-005 и LM-006 выглядят независимыми до тех пор, пока система не начинает писать в закрытые журналы после завершения операций.', items:['LM-005 → NORM-0','LM-006 → arithmetic listener','совпадение не равно общей сущности'] },
  { id:'T-LEGACY', title:'УДАЛЁННОЕ ПОКОЛЕНИЕ', copy:'AG-04, AG-09 и AG-13 принадлежат предыдущим поколениям Н.О.Р.М. Их истории не заменяют и не переписывают современную группу LM.', items:['2004 → NO-17','2009/2011 → AR-31','2013/2014 → IMG-13'] },
  { id:'T-11MIN', title:'ОДИННАДЦАТЬ МИНУТ', copy:'Повторяющееся временное смещение — самая сильная общая корреляция исторических материалов, но его причина не установлена.', items:['разрыв связи','timestamp drift','missing frame index'] },
  { id:'T-SYSTEM', title:'АРХИВ НАБЛЮДАЕТ', copy:'NORM-0, PID 0, GHOSTFS и MIRROR образуют системный слой загадки. Неясно, является ли он причиной, свидетелем или механизмом сохранения.', items:['owner: none','routes deleted, blocks remain','observer session'] },
]
